- name: check if aws cil is installed
  command: "aws"
  register: aws_result
  changed_when: false
  failed_when: false

- name: install cli
  include_tasks: install-cli.yml
  when: "'No such file' in aws_result.msg"